import type { Anomaly } from './anomalyDetection.js';

interface DailyEmailData {
  date: string;
  summary: string;
  highlights: { label: string; value: string; trend?: string; sentiment: string }[];
  recommendations: {
    priority: string;
    category: string;
    text: string;
    potentialSavings?: number;
  }[];
  anomalies: Anomaly[];
  narrative: string;
}

interface WeeklyEmailData extends DailyEmailData {
  goalProgress?: { goalName: string; progressPct: number; onTrack: boolean; note: string }[];
  investmentSummary?: {
    totalValue: number;
    totalGain: number;
    returnPct: number;
    periodChange: number;
  } | null;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function sentimentColor(sentiment: string): string {
  switch (sentiment) {
    case 'positive':
      return '#16a34a';
    case 'negative':
      return '#dc2626';
    default:
      return '#6b7280';
  }
}

function priorityBadge(priority: string): string {
  const colors: Record<string, string> = {
    high: '#dc2626',
    medium: '#f59e0b',
    low: '#6b7280',
  };
  const color = colors[priority] ?? '#6b7280';
  return `<span style="background:${color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;">${priority.toUpperCase()}</span>`;
}

function trendArrow(trend?: string): string {
  if (trend === 'up') return '↑';
  if (trend === 'down') return '↓';
  return '→';
}

function baseLayout(title: string, content: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:24px;">
    <div style="background:#18181b;color:white;padding:20px 24px;border-radius:12px 12px 0 0;">
      <h1 style="margin:0;font-size:20px;font-weight:600;">🍽️ Free Lunch</h1>
      <p style="margin:4px 0 0;font-size:14px;color:#a1a1aa;">${escapeHtml(title)}</p>
    </div>
    <div style="background:white;padding:24px;border-radius:0 0 12px 12px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
      ${content}
    </div>
    <p style="text-align:center;font-size:12px;color:#9ca3af;margin-top:16px;">
      Generated by Free Lunch Finance Advisor
    </p>
  </div>
</body>
</html>`;
}

export function buildDailyEmailHtml(data: DailyEmailData): string {
  const highlightsHtml = data.highlights
    .map(
      (h) =>
        `<div style="display:inline-block;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:12px 16px;margin:4px;">
          <div style="font-size:12px;color:#6b7280;">${escapeHtml(h.label)}</div>
          <div style="font-size:18px;font-weight:600;color:${sentimentColor(h.sentiment)};">${escapeHtml(h.value)} ${trendArrow(h.trend)}</div>
        </div>`
    )
    .join('');

  const recsHtml = data.recommendations
    .map(
      (r) =>
        `<li style="margin-bottom:8px;">
          ${priorityBadge(r.priority)} ${escapeHtml(r.text)}
          ${r.potentialSavings ? `<span style="color:#16a34a;font-size:13px;"> (save ~€${r.potentialSavings.toFixed(0)})</span>` : ''}
        </li>`
    )
    .join('');

  const anomalyHtml =
    data.anomalies.length > 0
      ? `<h3 style="margin:20px 0 8px;font-size:16px;">⚠️ Anomalies</h3>
         <ul style="padding-left:20px;margin:0;">${data.anomalies
           .map((a) => `<li style="margin-bottom:4px;color:${a.severity === 'alert' ? '#dc2626' : a.severity === 'warning' ? '#f59e0b' : '#6b7280'};">${escapeHtml(a.description)}</li>`)
           .join('')}</ul>`
      : '';

  const narrativeHtml = data.narrative
    .split('\n\n')
    .map((p) => `<p style="margin:8px 0;line-height:1.6;color:#374151;">${escapeHtml(p)}</p>`)
    .join('');

  const content = `
    <p style="font-size:16px;font-weight:600;color:#111827;margin:0 0 12px;">${escapeHtml(data.summary)}</p>
    <div style="margin:16px 0;">${highlightsHtml}</div>
    ${anomalyHtml}
    ${recsHtml ? `<h3 style="margin:20px 0 8px;font-size:16px;">💡 Recommendations</h3><ul style="padding-left:20px;margin:0;">${recsHtml}</ul>` : ''}
    <h3 style="margin:20px 0 8px;font-size:16px;">📊 Analysis</h3>
    ${narrativeHtml}
  `;

  return baseLayout(`Daily Update — ${data.date}`, content);
}

interface ConsentExpiryEmailData {
  bankName: string;
  expiresAt: Date;
  daysLeft: number;
  settingsUrl: string;
}

export function buildConsentExpiryEmailHtml(data: ConsentExpiryEmailData): string {
  const expiryDate = data.expiresAt.toLocaleDateString('en-GB', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const content = `
    <p style="font-size:16px;font-weight:600;color:#111827;margin:0 0 12px;">
      Your bank connection needs renewing
    </p>
    <p style="margin:8px 0;line-height:1.6;color:#374151;">
      Your connection to <strong>${escapeHtml(data.bankName)}</strong> expires in
      <strong>${data.daysLeft} day${data.daysLeft === 1 ? '' : 's'}</strong> (on ${escapeHtml(expiryDate)}).
    </p>
    <p style="margin:8px 0;line-height:1.6;color:#374151;">
      Banking rules (PSD2) require you to re-authorize access every 90 days. Once the
      connection expires, automatic transaction sync stops until you reconnect.
      Reconnecting takes under a minute — you'll be sent to your bank to confirm.
    </p>
    <div style="margin:20px 0;text-align:center;">
      <a href="${escapeHtml(data.settingsUrl)}"
         style="display:inline-block;background:#18181b;color:white;text-decoration:none;
                padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px;">
        Reconnect ${escapeHtml(data.bankName)}
      </a>
    </div>
  `;

  return baseLayout('Bank connection expiring soon', content);
}

interface InvitationEmailData {
  inviterName?: string;
  inviterEmail?: string;
  inviteeEmail: string;
  role: 'editor' | 'viewer';
  appUrl: string;
}

export function buildInvitationEmailHtml(data: InvitationEmailData): string {
  const inviter = data.inviterName
    ? `${data.inviterName}${data.inviterEmail ? ` (${data.inviterEmail})` : ''}`
    : (data.inviterEmail ?? 'A Free Lunch user');
  const roleDescription =
    data.role === 'editor'
      ? 'an editor — you will be able to view and edit their transactions, categories, and budgets'
      : 'a viewer — you will be able to view their transactions and reports';

  const content = `
    <p style="font-size:16px;font-weight:600;color:#111827;margin:0 0 12px;">
      You've been invited to share a household on Free Lunch
    </p>
    <p style="margin:8px 0;line-height:1.6;color:#374151;">
      <strong>${escapeHtml(inviter)}</strong> has invited you to share their household
      finances in Free Lunch, a personal finance app. You've been invited as
      ${escapeHtml(roleDescription)}.
    </p>
    <p style="margin:8px 0;line-height:1.6;color:#374151;">
      To accept, sign in to Free Lunch — or create an account — using
      <strong>this email address (${escapeHtml(data.inviteeEmail)})</strong>.
      The invitation is matched to this exact address, so it will be waiting for you
      when you sign in.
    </p>
    <div style="margin:20px 0;text-align:center;">
      <a href="${escapeHtml(data.appUrl)}"
         style="display:inline-block;background:#18181b;color:white;text-decoration:none;
                padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px;">
        Open Free Lunch
      </a>
    </div>
    <p style="margin:8px 0;line-height:1.6;color:#6b7280;font-size:13px;">
      If you weren't expecting this invitation, you can safely ignore this email.
    </p>
  `;

  return baseLayout('Household sharing invitation', content);
}

export function buildWeeklyEmailHtml(data: WeeklyEmailData): string {
  // Reuse daily template structure with added sections
  let extraSections = '';

  if (data.goalProgress && data.goalProgress.length > 0) {
    const goalsHtml = data.goalProgress
      .map((g) => {
        const barColor = g.onTrack ? '#16a34a' : '#f59e0b';
        return `<div style="margin-bottom:12px;">
          <div style="display:flex;justify-content:space-between;font-size:14px;margin-bottom:4px;">
            <span>${escapeHtml(g.goalName)}</span>
            <span style="color:${barColor};">${g.progressPct.toFixed(0)}%</span>
          </div>
          <div style="background:#e5e7eb;border-radius:4px;height:8px;">
            <div style="background:${barColor};border-radius:4px;height:8px;width:${Math.min(100, g.progressPct)}%;"></div>
          </div>
          <div style="font-size:12px;color:#6b7280;margin-top:2px;">${escapeHtml(g.note)}</div>
        </div>`;
      })
      .join('');
    extraSections += `<h3 style="margin:20px 0 8px;font-size:16px;">🎯 Goal Progress</h3>${goalsHtml}`;
  }

  if (data.investmentSummary) {
    const inv = data.investmentSummary;
    const gainColor = inv.totalGain >= 0 ? '#16a34a' : '#dc2626';
    extraSections += `<h3 style="margin:20px 0 8px;font-size:16px;">📈 Investments</h3>
      <div style="background:#f9fafb;border-radius:8px;padding:16px;">
        <div style="font-size:24px;font-weight:600;">€${inv.totalValue.toFixed(2)}</div>
        <div style="color:${gainColor};font-size:14px;">
          ${inv.totalGain >= 0 ? '+' : ''}€${inv.totalGain.toFixed(2)} (${inv.returnPct.toFixed(1)}%)
          · Week: ${inv.periodChange >= 0 ? '+' : ''}€${inv.periodChange.toFixed(2)}
        </div>
      </div>`;
  }

  // Build using daily template as base
  const dailyHtml = buildDailyEmailHtml(data);
  // Insert extra sections before the analysis heading
  return dailyHtml.replace(
    '<h3 style="margin:20px 0 8px;font-size:16px;">📊 Analysis</h3>',
    `${extraSections}<h3 style="margin:20px 0 8px;font-size:16px;">📊 Analysis</h3>`
  );
}
