name: FreeLunch
options:
  bundleIdPrefix: com.freelunch
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 10.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    version: 7.0.0

targets:
  FreeLunch:
    type: application
    platform: iOS
    sources:
      - path: FreeLunch
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.freelunch.app
        INFOPLIST_FILE: FreeLunch/Info.plist
        CODE_SIGN_ENTITLEMENTS: FreeLunch/FreeLunch.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseMessaging
      - package: Firebase
        product: FirebaseFunctions
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - target: FreeLunchWidgets
        embed: true
    postCompileScripts:
      - script: |
          # Firebase Crashlytics Run Script (optional)
          # "${PODS_ROOT}/FirebaseCrashlytics/run"
        name: Firebase Crashlytics
        runOnlyWhenInstalling: false

  FreeLunchWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: FreeLunchWidgets
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.freelunch.app.widgets
        INFOPLIST_FILE: FreeLunchWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: FreeLunchWidgets/FreeLunchWidgets.entitlements
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SKIP_INSTALL: true

  FreeLunchTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FreeLunchTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.freelunch.app.tests
        INFOPLIST_FILE: FreeLunchTests/Info.plist
    dependencies:
      - target: FreeLunch

  FreeLunchUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FreeLunchUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.freelunch.app.uitests
        INFOPLIST_FILE: FreeLunchUITests/Info.plist
    dependencies:
      - target: FreeLunch

schemes:
  FreeLunch:
    build:
      targets:
        FreeLunch: all
        FreeLunchTests: [test]
        FreeLunchUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FreeLunchTests
        - FreeLunchUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
